//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClotheOurKids.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chapter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chapter()
        {
            this.ChapterCounties = new HashSet<ChapterCounty>();
            this.ChapterOffices = new HashSet<ChapterOffice>();
        }
    
        public int ChapterId { get; set; }
        public short OfficeId { get; set; }
        public int MailingAddressId { get; set; }
        public System.DateTime IncorporatedDate { get; set; }
        public short IncorporatedStateId { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChapterCounty> ChapterCounties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChapterOffice> ChapterOffices { get; set; }
        public virtual State State { get; set; }
        public virtual Office Office { get; set; }
    }
}
