//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClotheOurKids.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NeededItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NeededItem()
        {
            this.Requests = new HashSet<Request>();
        }
    
        public int NeededItemsId { get; set; }
        public bool ShirtFlag { get; set; }
        public bool PantFlag { get; set; }
        public bool UnderwearFlag { get; set; }
        public bool SockFlag { get; set; }
        public bool ShoeFlag { get; set; }
        public bool CoatFlag { get; set; }
        public bool HygieneFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
    }
}
