//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClotheOurKids.Model.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PositionOfficeType
    {
        public int PositionOfficeTypeId { get; set; }
        public short PositionId { get; set; }
        public byte OfficeTypeId { get; set; }
    
        public virtual OfficeType OfficeType { get; set; }
        public virtual Position Position { get; set; }
    }
}
