//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClotheOurKids.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestId { get; set; }
        public System.DateTime DateRequested { get; set; }
        public System.DateTime DateEstimatedDelivery { get; set; }
        public System.DateTime DateDelivered { get; set; }
        public string SubmittedByUserId { get; set; }
        public byte RequestStatusId { get; set; }
        public Nullable<short> SchoolId { get; set; }
        public string GenderId { get; set; }
        public short GradeId { get; set; }
        public byte UrgencyId { get; set; }
        public Nullable<int> ShirtSizeId { get; set; }
        public Nullable<int> PantSizeId { get; set; }
        public Nullable<int> PantLengthSizeId { get; set; }
        public string UnderwearSize { get; set; }
        public string ShoeSize { get; set; }
        public bool HygieneKitFlag { get; set; }
        public string Comments { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Grade Grade { get; set; }
        public virtual PantSize PantSize { get; set; }
        public virtual PantSize PantSize1 { get; set; }
        public virtual School School { get; set; }
        public virtual ShirtSize ShirtSize { get; set; }
        public virtual Urgency Urgency { get; set; }
        public virtual RequestStatus RequestStatus { get; set; }
    }
}
