//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClotheOurKids.Model.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolType
    {
        public byte SchoolTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}
